### ISSUE TITLE
Vaisala RS41 fw dump

### ISSUE THREAD

**Issue by analogic** [bazjo/radiosonde_hardware#19]
Hello @bazjo,
I've successfully dumped RS41 - please see https://analogic.cz/rs41-rpm411/
I've also spent some time with Ghidra and decoding what firmware does, but it is lenghty process thats why I'm giving it public so others might also enjoy reversing

**Comment by DJTacki** [comment]
Hello @analogic,

Do you have any progress on decoding the binary? I'll try to collaborate.

**Comment by analogic** [comment]
@DJTacki Sorry, I had the most fun breaking the STM lock and dumping the firmware. I have other projects to work on, but there's an uncertain time in the future when I'll get back to reverse engineering...

**Comment by DJTacki** [comment]
@analogic Thank you for the reply, we are in the same boat :) I'll let you know if I have any progress in Ghidra, please do the same.
